# Default initial positions for fanuc_m20ia_35m's ros2_control fake system

initial_positions:
  fanuc_m20ia_35m_joint1: 0
  fanuc_m20ia_35m_joint2: 0
  fanuc_m20ia_35m_joint3: 0
  fanuc_m20ia_35m_joint4: 0
  fanuc_m20ia_35m_joint5: 0
  fanuc_m20ia_35m_joint6: 0
  joint_world_to_slider: 0