# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - fanuc_m20ia_35m_slide_to_end_effector_controller

  fanuc_m20ia_35m_slide_to_end_effector_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_world_to_slider
      - fanuc_m20ia_35m_joint1
      - fanuc_m20ia_35m_joint2
      - fanuc_m20ia_35m_joint3
      - fanuc_m20ia_35m_joint4
      - fanuc_m20ia_35m_joint5
      - fanuc_m20ia_35m_joint6