# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    fanuc_m20ia_35m_slide_to_end_effector_controller:
      type: velocity_controller/VelocityController
    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


fanuc_m20ia_35m_slide_to_end_effector_controller:
  ros__parameters:
    controller_gain: [200.0, 200.0, 200.0, 40.0, 40.0, 40.0]
    joint_model_group_name: "fanuc_m20ia_35m_slide_to_fastening"
    robot_description: "robot_description"
    frequency: 1000
    position_tolerance: 0.01
    angle_tolerance: 0.01
